import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
  // By default, Docusaurus generates a sidebar from the docs folder structure
 const sidebars: SidebarsConfig = {
  features: [{ type: 'autogenerated', dirName: 'features' }],
  data: [{ type: 'autogenerated', dirName: 'data_streams' }],
  workflows: [{ type: 'autogenerated', dirName: 'workflows' }],
};

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

export default sidebars;
