import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Quick Links',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: '02-quick_links' },
        {
          type: 'link',
          label: 'Publications with LAMP',
          href: 'https://www.digitalpsych.org/mindlamp-publications.html',
        },
      ],
    },

    // Autogenerate the rest of the top-level sections
    { type: 'autogenerated', dirName: '05-using' },
    { type: 'autogenerated', dirName: '06-start_here' },
    { type: 'autogenerated', dirName: '08-develop' },
    { type: 'autogenerated', dirName: '09-data_science' },
  ],
};

export default sidebars;
