import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'Publications with LAMP',
      href: 'https://www.digitalpsych.org/mindlamp-publications.html',
    },
  ],
};

export default sidebars;
