# Workflows

Workflows are **task-oriented guides** that walk through multi-step processes.

Examples of workflows you might document here:
- Onboarding participants into a study
- Troubleshooting data quality
- Configuring Cortex queries
- Setting up activities for a protocol
- Exporting and analyzing data

# Page Template
---
type: workflow
title: Workflow Name
slug: /workflows/workflow-name
platforms: [android, ios, web, watch, ...]
owner: your-name
lastReviewed: YYYY-MM-DD
related: []
evidence: []
tags: []
---

## Purpose
Explain when and why someone would use this workflow.

## Prerequisites
Accounts, permissions, devices, or other setup required.

## Steps
1. Step one…
2. Step two…
3. Expected result…

## Troubleshooting
Common pitfalls and fixes.

## Related
Cross-links to relevant Features or Data Streams.
