name: "New Data Stream Page"
description: Propose or update documentation for a Data Stream in mindLAMP
title: "New Data Stream] "
labels: ["docs", "needs info (docs)", "data stream (docs)"]
body:
  - type: input
    id: title
    attributes:
      label: Data Stream title
      placeholder: GPS, Accelerometer, EMA Responses, etc.
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      options: ["live","beta","planned","deprecated"]

  - type: checkboxes
    id: platforms
    attributes:
      label: Platforms
      options:
        - label: mindLAMP (ios)
        - label: mindLAMP (android)
        - label: dashboard (web)
        - label: database (server)
        - label: cortex

  - type: checkboxes
    id: devices
    attributes:
      label: Devices
      options:
        - label: apple phone
        - label: android phone
        - label: apple wearable
        - label: other wearable

  - type: textarea
    id: what-collected
    attributes:
      label: What is collected
      description: Sensor or event type.

  - type: textarea
    id: data-origin
    attributes:
      label: Data origin
      description: Where the data comes from (OS APIs, backend, user input).

  - type: textarea
    id: sampling
    attributes:
      label: Sampling behavior
      description: Frequency, triggers, platform differences.

  - type: textarea
    id: schema
    attributes:
      label: Schema
      description: Keys/fields, example JSON if possible.

  - type: textarea
    id: analysis
    attributes:
      label: Analysis notes
      description: How researchers use this data.

  - type: textarea
    id: limitations
    attributes:
      label: Known limitations

  - type: textarea
    id: verify
    attributes:
      label: Verification
      description: Steps to confirm it’s collected correctly.

  - type: textarea
    id: pubs
    attributes:
      label: Publications or references

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
